---
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - PEERS=10  #유저수에 따라 변경, 추후 Netbird를 통한 SSO 기반 접근 제한 구현 예정
      - SERVERPORT=51820
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=10.8.0.0
    volumes:
      - /data/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped