loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: oci-bv
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 300m
      memory: 500Mi

promtail:
  enabled: true
  extraScrapeConfigs: []
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 300m
      memory: 500Mi

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: oci-bv
  sidecar:
    datasources:
      enabled: true
      searchNamespace: ALL
    dashboards:
      enabled: true
      searchNamespace: ALL
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 300m
      memory: 500Mi

prometheus:
  enabled: true
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 300m
      memory: 500Mi
  extraScrapeConfigs: |
    - job_name: 'conner-backend'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['conner-backend.conner.default.svc.cluster.local:8081']
    - job_name: 'danuri-backend-prod'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['danuri-prod.danuri-prod.default.svc.cluster.local:8081']
    - job_name: 'danuri-backend-stage'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['danuri-stage.danuri-stage.default.svc.cluster.local:8081']
