version: "3.3"

services:
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 8080:2368
    volumes:
      - ~/data/content:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ${PASSWORD}
      database__connection__database: ghost
      url: https://test.sver.dev
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ~/data/db:/var/lib/mysql
    ports:
      - 13928:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${PASSWORD}
