apiVersion: apps/v1
kind: Deployment
metadata:
  name: socchat-backend
  namespace: socchat
  labels:
    app: socchat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socchat-backend
  template:
    metadata:
      labels:
        app: socchat-backend
    spec:
      imagePullSecrets:
        - name: socchat-pull-secret
      containers:
        - name: socchat-backend
          image: ghcr.io/withjihyuk/supabase_upload_image:latest
          ports:
            - containerPort: 10001
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 10001
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 10001
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: socchat-backend
